extract coq functional,coverage semantics as haskell lib
harp-project/erlang-semantics-testing pull request #13
Opened 2021-01-16 10:53 UTC by Kokan

2021-01-19 11:24 UTC, berpeti requested changes
I have one general comment. Could we avoid duplicating the converter code (e.g. with preprocessing which tells the delimiters to be used)? Also, there is a lot of duplication between `execute_coq` and `execute_ghc`, maybe we could just export the functions from `execute_coq` which are used in `execute_ghc`.

2021-01-19 11:24 UTC, berpeti commented on execute_ghc.erl
> +  PID ! {execute(TestPath, BaseName, ReportDirectory, Tracing), ghc_res}.
Do not use `ghc_res` here. It should remain `coq_res` or maybe `core_erlang_res` both here and in `execute_coq`. It simplifies `receive`-s in `scripts.erl` when we allow to switch between Coq and Haskell.

2021-01-19 13:03 UTC, Kokan commented on execute_erl.erl
> +execute(Test, ModuleName, ReportDirectory, Tracing, PID) ->
well we should. the plan was to have some kind of interface that can be followed by executors. as such they are easy to replace. i had lot of trouble due to not conforming stuff like this...

2021-01-25 21:31 UTC, Kokan commented on execute_ghc.erl
> +  PID ! {execute(TestPath, BaseName, ReportDirectory, Tracing), ghc_res}.
done, although `ghc_res` imho better, if needed at all. the result compare is a mess currently, that should be improved instead of doing this renaming.

2021-01-25 21:31 UTC, Kokan commented on scripts.erl
> +    spawn(execute_ghc, execute, [BaseName, ModuleName, ReportDirectory, ?TRACING, self()]),
done.

2021-01-25 21:32 UTC, Kokan commented on ExtractBigStepSemanticsTraced.v
> +  (fbs_expr 100000 init_logs [] 0 expr []).
done.

2021-01-25 21:32 UTC, Kokan commented on ExtractBigStepSemantics.v
> +  (fbs_expr 100000 [] 0 expr []).
done.

2021-01-25 21:37 UTC, Kokan commented
> I have one general comment. Could we avoid duplicating the converter code (e.g. with preprocessing which tells the delimiters to be used)? Also, there is a lot of duplication between execute_coq and execute_ghc, maybe we could just export the functions from execute_coq which are used in execute_ghc.

The converter now is very similar, and most cases only a delimiter would suffice. I would rather not make that move, as it just happens to be the same-ish structure due to how currently the coq -> haskell extraction works. The way how extraction work may change, due to Coq or just us replacing a sub-expression with different haskell implementation, realizing that code should be really different and copy is not so harsh here.

The execute_coq <> execute_ghc part I did, as the output of the extracted haskell and coq should be the same, otherwise something probably went wrong during extraction.

2021-01-27 11:54 UTC, berpeti approved these changes

2021-01-27 12:44 UTC, merged